"""List every difference between the proof as sent and the proof as answered.

The editorial office allows either tracked changes or a list of changes. Word's own
find-and-replace destroys editorial comments whose anchors fall inside a replaced range,
which is why the edits were made in the XML instead, and that leaves no tracked changes to
show. So the list is generated from the two files rather than written by hand: it cannot
omit a change that was made, and it cannot claim one that was not.

    python paper/proof/make_change_list.py
"""

from __future__ import annotations

import difflib
import re
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
BEFORE = HERE / "jimaging-4539482-for proof.docx"
AFTER = HERE / (sys.argv[1] if len(sys.argv) > 1 else "jimaging-4539482-final.docx")
OUT = HERE / "CHANGES_FOR_EDITOR.txt"

PARA = re.compile(r"<w:p(?: [^>]*)?>.*?</w:p>|<w:p(?: [^>]*)?/>", re.S)


def paragraphs(path: Path) -> list[str]:
    document = zipfile.ZipFile(path).read("word/document.xml").decode("utf-8")
    out = []
    for block in PARA.findall(document):
        text = re.sub(r"\s+", " ", "".join(re.findall(r"<w:t[^>]*>([^<]*)</w:t>", block))).strip()
        if text:
            out.append(text)
    return out


def phrase_diff(old: str, new: str) -> str:
    """The changed words only, with a little context, rather than the whole paragraph."""
    words = difflib.SequenceMatcher(None, old.split(), new.split(), autojunk=False)
    parts = []
    for tag, i1, i2, j1, j2 in words.get_opcodes():
        if tag == "equal":
            continue
        before = " ".join(old.split()[max(0, i1 - 5) : i1])
        removed = " ".join(old.split()[i1:i2])
        added = " ".join(new.split()[j1:j2])
        after = " ".join(new.split()[j2 : j2 + 5])
        parts.append(f"      ...{before} [{removed or '-'}] -> [{added or '-'}] {after}...")
    return "\n".join(parts)


def main() -> int:
    before, after = paragraphs(BEFORE), paragraphs(AFTER)
    lines = [
        "Changes made to the proof of jimaging-4539482",
        "",
        "Generated by comparing the file you sent with the file returned, so that nothing",
        "is omitted and nothing is claimed that was not done. Every editorial comment is",
        "answered in its own thread in the file; none has been deleted.",
        "",
        "The two figures were replaced as whole images and so do not appear below:",
        "Figure 4, whose image in the proof carried no (a)/(b) labels and printed no value",
        "in the cells of the heat map although its caption says it does; and Figure 5, which",
        "now carries (a) to (d) and whose panel (d) has been relaid out so the legend and",
        "the annotations no longer crowd each other. Neither figure's data changed.",
        "",
        "The reference list has been reordered so that it runs in order of first citation,",
        "and all citations in the text were renumbered to match. Those renumberings are",
        "listed below with everything else.",
        "",
        "-" * 70,
        "",
    ]
    matcher = difflib.SequenceMatcher(None, before, after, autojunk=False)
    number = 0
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            continue
        number += 1
        old = " / ".join(before[i1:i2])
        new = " / ".join(after[j1:j2])
        lines.append(f"{number}. in: {(new or old)[:88]}")
        detail = phrase_diff(old, new)
        lines.append(detail if detail else f"      (moved) {old[:80]}")
        lines.append("")
    lines += ["-" * 70, "", f"{number} places changed."]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\r\n")
    print(f"{number} places changed; written to {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
